[package]
name = "athena_viewer"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.29.0"
ratatui = "0.29.0"
tui-input = "0.14.0"
chrono = { version = "0.4", features = ["serde"] }
lru = "0.16.2"
